name: puc_flutter_virtual
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  http: ^1.2.2
  latlong2: ^0.9.1
  location: ^6.0.2
  path: ^1.9.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
